# c/Makefile
slice: slice.c
	$(CC) -Wall -O2 -o slice slice.c

slice1: slice1.c
	$(CC) -Wall -O2 -o slice1 slice1.c

slice2: slice2.c
	$(CC) -Wall -O2 -o slice2 slice2.c

slice3: slice3.c
	$(CC) -Wall -O2 -o slice3 slice3.c

